urls.py
from django.urls import path
from . import views

app_name='polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name="details"),
    path('<int:question_id>/result/',views.result, name="result"),
    path('details',views.detail,name="detail"),
    path('<int:question_id>/vote/', views.vote ,name="vote"),
]

models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib import admin


# Create your models here.
# in question class - question and publication datetime
# in choice class - choice txt and votes 
class Questions(models.Model):        # models.model it means it inherite the model class 
    ques_txt=models.CharField(max_length=200)        # charfield and datetimefield  denotes datatypes of question and time  
    publ_time=models.DateTimeField(default=timezone.now())  # now() represent  current timing of raising a qustion by user 
    #def __str__(self):
        #return self.ques_txt
        
    @admin.display(
        boolean=True,
        ordering='publ_time',
        description='published recently?',
    )
    
    def was_question_recently_published(self):
        return self.publ_time>= timezone.now()-datetime.timedelta(1)
    
    
    
    
class Choice(models.Model):
    choice_txt=models.CharField(max_length=200)
    votes=models.IntegerField(default=1)
    question=models.ForeignKey(Questions,on_delete=models.CASCADE)      # this line coonets thse two classes , forigenkey inherit the Questions  
   # (on_delete=models.cascade) it means if questions is deleted then there votes for question is pointingless thats why we used  this  & CASCADE its is proceed one by one   
    def __str__(self):
        return self.choice_txt
    

views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from .models import Questions
from .models import Choice
from django.urls import reverse
from django.template import loader

def index (request):
    latest_ques_list=Questions.objects.order_by('publ_time')[0:5]
    template=loader.get_template("polls/index.html")
    context={
        'latest_ques_list':latest_ques_list,
    }
    return HttpResponse(template.render(context,request))

def detail(request, question_id):
    try:
        question=Questions.objects.get(pk=question_id)
    except Questions.DoesNotExist :
        raise Http404("Question is does not exist in database")
    return render(request, "polls/detail.html", {"question": question})

def result(request,question_id):
    question=get_object_or_404(Questions,pk=question_id)
    return render(request,"polls/result.html",{"question": question})

def vote(request , question_id):
    
    print(f"Vote view called with method: {request.method}")
    print(f"POST data: {request.POST}")
    # ... rest of your code
    #return HttpResponse("your looking at votes"%question_id)
    question=get_object_or_404(Questions,pk=question_id )
    try:
        
        selected_choice_id = request.POST['choice']
        selected_choice = question.choice_set.get(pk=selected_choice_id)
        #selected_choice=question.choice_set.get(pk=request.POST["Choice"])
        

        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:result",args=(question_id)))
        #return HttpResponse(template.render(context,request))
    #except:
        #return render(request,"polls/result.html",{"question":question,"error_message":"request is not valid"})
    
    except KeyError:
        return render(request, "polls/result.html", {
        "question": question,
        "error_message": "You didn't select a choice.",
        })
    except Choice.DoesNotExist:
        return render(request, "polls/result.html", {
        "question": question,
        "error_message": "Selected choice does not exist.",
        })

    
    

templates/polls/detail.html
{% comment "" %}<html>
    <head>
        <title> choice app </title>
    </head>
    <body>
        <h1>
            {{question.ques_txt}} </h1>
            <ul>
                {% for choice in question.choice_set.all %}
                <li> {{ choice.choice_txt }} </li>
                {% endfor%}
            </ul>
    </body>
</html> {% endcomment %}
<html>
    <head>
    <title>
        the details</title>
    </head>
    <body>
        <form action="{% url "polls:vote" question.id%}" method="POST">
            {% csrf_token %}  
            <fieldset>
                <legend> <h1> {{ question.ques_txt }} </h1> </legend>
                {% if error_message %}
                    <p> <strong> {{error_message}} </strong> </p>
                {% endif %}
                {% for choice in question.choice_set.all %}
                    {% comment%}<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" >  {% endcomment %}
                    <input type="radio" name="choice"  value="{{ choice.id }}" >
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_txt }}</label><br>

                    

                {% endfor %}
            </fieldset>
            <br>
            <input type="submit" value="vote">

            
        </form>
        <p><a href="{% url 'polls:details' question.id %}"> vote again? </p>
        <p><a href="{% url 'polls:index' %}"> home </p>


    </body>
</html>

templates/polls/index.html
<html>
<head>
    polls app
    
</head>
{% load static %}
<link rel="stylesheet" href="{% static "polls/style.css"%}">
<body>
    {% if latest_ques_list %}
    <ul>
    {% for question in latest_ques_list %}
        {% comment "" %}<li><a href="/polls/{{ question.id }}/">{{ question.ques_txt }}</a></li> {% endcomment %}
        {% comment "" %} <li><a href="/{{question.id}}/">{{question.ques_txt}}</li>  {% endcomment %} 
        
        <li><a href={% url 'polls:details' question.id%}> {{question.ques_txt}} </li>

    {% endfor %}
    </ul>
    {% else %}
         <p>No polls are available.</p>
    {% endif %}
</body>
</head>
</html>

templates/polls/result.html
<html>
    <head>
        <title> Results </title>
    </head>
    <body>
        <h1> {{question.ques_txt}}</h1>
        <ul>
            {% for choice in question.choice_set.all %}
                <li> {{choice.choice_txt}} -- {{choice.votes}} vote{{choice.votes|pluralize}} </li>
            {% endfor%}
        </ul>
        <p><a href="{% url 'polls:index' %}"> wanna votes for another question </p>
    </body>
</html>